// ============================================================
// CITY SALARY DATA — BLS OEWS May 2025 (real, verified)
// salaryfact.com
// 181 US metros
//
// Source: BLS Occupational Employment and Wage Statistics, May 2025
// release, "All Occupations" row (OCC_CODE 00-0000). Metro area file:
// https://www.bls.gov/oes/special-requests/oesm25ma.zip
// Downloaded and parsed directly, not estimated. Replaces a prior
// version whose 181 medianSalary values were invented placeholder
// figures, not real BLS output - audited and rebuilt 2026-08-31, same
// pass as lib/salary-data.ts (see that file's header for the national/
// state fix).
//
// Two-tier sourcing, since not every city in this list has its own
// BLS metro area:
//   1. 141 cities matched to a real BLS Metropolitan Statistical Area
//      by name (e.g. "Houston" -> "Houston-Pasadena-The Woodlands, TX").
//      Many entries here are suburbs that share their parent metro's
//      real MSA figure (e.g. "North Las Vegas" uses the same real
//      "Las Vegas-Henderson-North Las Vegas, NV" MSA median as
//      "Las Vegas" - they are literally the same BLS metro area, not
//      a data error).
//   2. 40 smaller cities have no distinct BLS metro area in the OEWS
//      May 2025 file (too small, or absorbed into a larger metro
//      whose title doesn't name them specifically - e.g. Yonkers is
//      inside the "New York-Newark-Jersey City" MSA but isn't named in
//      its title). These use the real state median from
//      STATE_MEDIAN_SALARIES in salary-data.ts instead of a guessed
//      number - state-level real BLS data, not a fabricated city
//      figure. A future pass could improve these with BLS's Balance-
//      of-State sub-regional file if precision here becomes a priority.
//
// Also fixed here: the "tucson-extra" slug actually held Mesa, AZ data
// (a copy-paste artifact from an earlier version of this file) -
// renamed to "mesa" so its URL matches its content.
// ============================================================

export interface CityData {
  name: string;
  state: string;
  stateCode: string;
  medianSalary: number;
  population: number;
}

export const CITY_DATA: Record<string, CityData> = {
  "houston": {
    name: "Houston",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 49410,
    population: 2304580,
  },
  "san-antonio": {
    name: "San Antonio",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 47010,
    population: 1434625,
  },
  "dallas": {
    name: "Dallas",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 51440,
    population: 1304379,
  },
  "austin": {
    name: "Austin",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 56950,
    population: 961855,
  },
  "fort-worth": {
    name: "Fort Worth",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 51440,
    population: 927720,
  },
  "phoenix": {
    name: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 51380,
    population: 1608139,
  },
  "tucson": {
    name: "Tucson",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 47760,
    population: 542629,
  },
  "los-angeles": {
    name: "Los Angeles",
    state: "California",
    stateCode: "CA",
    medianSalary: 55850,
    population: 3979576,
  },
  "san-diego": {
    name: "San Diego",
    state: "California",
    stateCode: "CA",
    medianSalary: 58690,
    population: 1386932,
  },
  "san-francisco": {
    name: "San Francisco",
    state: "California",
    stateCode: "CA",
    medianSalary: 74260,
    population: 873965,
  },
  "sacramento": {
    name: "Sacramento",
    state: "California",
    stateCode: "CA",
    medianSalary: 59750,
    population: 524943,
  },
  "denver": {
    name: "Denver",
    state: "Colorado",
    stateCode: "CO",
    medianSalary: 62320,
    population: 715522,
  },
  "chicago": {
    name: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    medianSalary: 54720,
    population: 2693976,
  },
  "atlanta": {
    name: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    medianSalary: 51170,
    population: 498715,
  },
  "miami": {
    name: "Miami",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 48640,
    population: 467963,
  },
  "tampa": {
    name: "Tampa",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 48940,
    population: 399700,
  },
  "orlando": {
    name: "Orlando",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 46630,
    population: 307573,
  },
  "jacksonville": {
    name: "Jacksonville",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 48830,
    population: 949611,
  },
  "charlotte": {
    name: "Charlotte",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 49990,
    population: 874579,
  },
  "raleigh": {
    name: "Raleigh",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 51990,
    population: 467665,
  },
  "nashville": {
    name: "Nashville",
    state: "Tennessee",
    stateCode: "TN",
    medianSalary: 50390,
    population: 689447,
  },
  "memphis": {
    name: "Memphis",
    state: "Tennessee",
    stateCode: "TN",
    medianSalary: 46890,
    population: 633104,
  },
  "las-vegas": {
    name: "Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    medianSalary: 46670,
    population: 641903,
  },
  "seattle": {
    name: "Seattle",
    state: "Washington",
    stateCode: "WA",
    medianSalary: 72610,
    population: 737255,
  },
  "portland": {
    name: "Portland",
    state: "Oregon",
    stateCode: "OR",
    medianSalary: 60690,
    population: 652503,
  },
  "minneapolis": {
    name: "Minneapolis",
    state: "Minnesota",
    stateCode: "MN",
    medianSalary: 59320,
    population: 429606,
  },
  "columbus": {
    name: "Columbus",
    state: "Ohio",
    stateCode: "OH",
    medianSalary: 51340,
    population: 905748,
  },
  "indianapolis": {
    name: "Indianapolis",
    state: "Indiana",
    stateCode: "IN",
    medianSalary: 49340,
    population: 887642,
  },
  "detroit": {
    name: "Detroit",
    state: "Michigan",
    stateCode: "MI",
    medianSalary: 52080,
    population: 632464,
  },
  "philadelphia": {
    name: "Philadelphia",
    state: "Pennsylvania",
    stateCode: "PA",
    medianSalary: 54310,
    population: 1603797,
  },
  "new-york-city": {
    name: "New York City",
    state: "New York",
    stateCode: "NY",
    medianSalary: 61430,
    population: 120000,
  },
  "boston": {
    name: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    medianSalary: 66620,
    population: 675647,
  },
  "baltimore": {
    name: "Baltimore",
    state: "Maryland",
    stateCode: "MD",
    medianSalary: 59070,
    population: 585708,
  },
  "louisville": {
    name: "Louisville",
    state: "Kentucky",
    stateCode: "KY",
    medianSalary: 48370,
    population: 633045,
  },
  "kansas-city": {
    name: "Kansas City",
    state: "Missouri",
    stateCode: "MO",
    medianSalary: 50820,
    population: 508090,
  },
  "salt-lake-city": {
    name: "Salt Lake City",
    state: "Utah",
    stateCode: "UT",
    medianSalary: 55240,
    population: 213641,
  },
  "richmond": {
    name: "Richmond",
    state: "Virginia",
    stateCode: "VA",
    medianSalary: 51460,
    population: 120000,
  },
  "albuquerque": {
    name: "Albuquerque",
    state: "New Mexico",
    stateCode: "NM",
    medianSalary: 48060,
    population: 564559,
  },
  "oklahoma-city": {
    name: "Oklahoma City",
    state: "Oklahoma",
    stateCode: "OK",
    medianSalary: 47230,
    population: 681054,
  },
  "milwaukee": {
    name: "Milwaukee",
    state: "Wisconsin",
    stateCode: "WI",
    medianSalary: 51160,
    population: 577222,
  },
  "montgomery": {
    name: "Montgomery",
    state: "Alabama",
    stateCode: "AL",
    medianSalary: 44950,
    population: 199518,
  },
  "huntsville": {
    name: "Huntsville",
    state: "Alabama",
    stateCode: "AL",
    medianSalary: 51740,
    population: 120000,
  },
  "mobile": {
    name: "Mobile",
    state: "Alabama",
    stateCode: "AL",
    medianSalary: 47000,
    population: 187041,
  },
  "tuscaloosa": {
    name: "Tuscaloosa",
    state: "Alabama",
    stateCode: "AL",
    medianSalary: 45220,
    population: 120000,
  },
  "fairbanks": {
    name: "Fairbanks",
    state: "Alaska",
    stateCode: "AK",
    medianSalary: 61810,
    population: 31757,
  },
  "juneau": {
    name: "Juneau",
    state: "Alaska",
    stateCode: "AK",
    medianSalary: 61000,
    population: 32255,
  },
  "sitka": {
    name: "Sitka",
    state: "Alaska",
    stateCode: "AK",
    medianSalary: 61000,
    population: 8756,
  },
  "ketchikan": {
    name: "Ketchikan",
    state: "Alaska",
    stateCode: "AK",
    medianSalary: 61000,
    population: 8250,
  },
  "fort-smith": {
    name: "Fort Smith",
    state: "Arkansas",
    stateCode: "AR",
    medianSalary: 39560,
    population: 88037,
  },
  "fayetteville": {
    name: "Fayetteville",
    state: "Arkansas",
    stateCode: "AR",
    medianSalary: 46610,
    population: 120000,
  },
  "springdale": {
    name: "Springdale",
    state: "Arkansas",
    stateCode: "AR",
    medianSalary: 46610,
    population: 87730,
  },
  "jonesboro": {
    name: "Jonesboro",
    state: "Arkansas",
    stateCode: "AR",
    medianSalary: 42240,
    population: 78576,
  },
  "new-haven": {
    name: "New Haven",
    state: "Connecticut",
    stateCode: "CT",
    medianSalary: 60060,
    population: 130322,
  },
  "hartford": {
    name: "Hartford",
    state: "Connecticut",
    stateCode: "CT",
    medianSalary: 59940,
    population: 121054,
  },
  "stamford": {
    name: "Stamford",
    state: "Connecticut",
    stateCode: "CT",
    medianSalary: 61470,
    population: 135470,
  },
  "waterbury": {
    name: "Waterbury",
    state: "Connecticut",
    stateCode: "CT",
    medianSalary: 51440,
    population: 120000,
  },
  "dover": {
    name: "Dover",
    state: "Delaware",
    stateCode: "DE",
    medianSalary: 46690,
    population: 120000,
  },
  "newark-de": {
    name: "Newark",
    state: "Delaware",
    stateCode: "DE",
    medianSalary: 52190,
    population: 33398,
  },
  "middletown": {
    name: "Middletown",
    state: "Delaware",
    stateCode: "DE",
    medianSalary: 52190,
    population: 120000,
  },
  "smyrna": {
    name: "Smyrna",
    state: "Delaware",
    stateCode: "DE",
    medianSalary: 52190,
    population: 120000,
  },
  "hilo": {
    name: "Hilo",
    state: "Hawaii",
    stateCode: "HI",
    medianSalary: 56320,
    population: 44060,
  },
  "kailua": {
    name: "Kailua",
    state: "Hawaii",
    stateCode: "HI",
    medianSalary: 56320,
    population: 38635,
  },
  "pearl-city": {
    name: "Pearl City",
    state: "Hawaii",
    stateCode: "HI",
    medianSalary: 56320,
    population: 47698,
  },
  "waipahu": {
    name: "Waipahu",
    state: "Hawaii",
    stateCode: "HI",
    medianSalary: 56320,
    population: 120000,
  },
  "meridian": {
    name: "Meridian",
    state: "Idaho",
    stateCode: "ID",
    medianSalary: 47970,
    population: 117635,
  },
  "nampa": {
    name: "Nampa",
    state: "Idaho",
    stateCode: "ID",
    medianSalary: 47970,
    population: 112300,
  },
  "idaho-falls": {
    name: "Idaho Falls",
    state: "Idaho",
    stateCode: "ID",
    medianSalary: 46800,
    population: 65274,
  },
  "pocatello": {
    name: "Pocatello",
    state: "Idaho",
    stateCode: "ID",
    medianSalary: 45160,
    population: 57776,
  },
  "cedar-rapids": {
    name: "Cedar Rapids",
    state: "Iowa",
    stateCode: "IA",
    medianSalary: 49360,
    population: 137710,
  },
  "davenport": {
    name: "Davenport",
    state: "Iowa",
    stateCode: "IA",
    medianSalary: 48550,
    population: 99685,
  },
  "sioux-city": {
    name: "Sioux City",
    state: "Iowa",
    stateCode: "IA",
    medianSalary: 47030,
    population: 82684,
  },
  "iowa-city": {
    name: "Iowa City",
    state: "Iowa",
    stateCode: "IA",
    medianSalary: 50060,
    population: 74398,
  },
  "overland-park": {
    name: "Overland Park",
    state: "Kansas",
    stateCode: "KS",
    medianSalary: 48010,
    population: 197238,
  },
  "topeka": {
    name: "Topeka",
    state: "Kansas",
    stateCode: "KS",
    medianSalary: 49540,
    population: 126587,
  },
  "olathe": {
    name: "Olathe",
    state: "Kansas",
    stateCode: "KS",
    medianSalary: 48010,
    population: 141290,
  },
  "lawrence": {
    name: "Lawrence",
    state: "Kansas",
    stateCode: "KS",
    medianSalary: 47390,
    population: 120000,
  },
  "baton-rouge": {
    name: "Baton Rouge",
    state: "Louisiana",
    stateCode: "LA",
    medianSalary: 48710,
    population: 227470,
  },
  "shreveport": {
    name: "Shreveport",
    state: "Louisiana",
    stateCode: "LA",
    medianSalary: 44820,
    population: 178097,
  },
  "lafayette": {
    name: "Lafayette",
    state: "Louisiana",
    stateCode: "LA",
    medianSalary: 41780,
    population: 120000,
  },
  "lake-charles": {
    name: "Lake Charles",
    state: "Louisiana",
    stateCode: "LA",
    medianSalary: 45700,
    population: 120000,
  },
  "lewiston": {
    name: "Lewiston",
    state: "Maine",
    stateCode: "ME",
    medianSalary: 49540,
    population: 120000,
  },
  "bangor": {
    name: "Bangor",
    state: "Maine",
    stateCode: "ME",
    medianSalary: 47960,
    population: 31753,
  },
  "south-portland": {
    name: "South Portland",
    state: "Maine",
    stateCode: "ME",
    medianSalary: 56960,
    population: 120000,
  },
  "auburn-me": {
    name: "Auburn",
    state: "Maine",
    stateCode: "ME",
    medianSalary: 49540,
    population: 24636,
  },
  "gulfport": {
    name: "Gulfport",
    state: "Mississippi",
    stateCode: "MS",
    medianSalary: 43470,
    population: 120000,
  },
  "southaven": {
    name: "Southaven",
    state: "Mississippi",
    stateCode: "MS",
    medianSalary: 40120,
    population: 120000,
  },
  "hattiesburg": {
    name: "Hattiesburg",
    state: "Mississippi",
    stateCode: "MS",
    medianSalary: 37750,
    population: 120000,
  },
  "biloxi": {
    name: "Biloxi",
    state: "Mississippi",
    stateCode: "MS",
    medianSalary: 43470,
    population: 120000,
  },
  "missoula": {
    name: "Missoula",
    state: "Montana",
    stateCode: "MT",
    medianSalary: 47830,
    population: 79966,
  },
  "great-falls": {
    name: "Great Falls",
    state: "Montana",
    stateCode: "MT",
    medianSalary: 46510,
    population: 59434,
  },
  "bozeman": {
    name: "Bozeman",
    state: "Montana",
    stateCode: "MT",
    medianSalary: 54830,
    population: 53293,
  },
  "butte": {
    name: "Butte",
    state: "Montana",
    stateCode: "MT",
    medianSalary: 48740,
    population: 35256,
  },
  "lincoln": {
    name: "Lincoln",
    state: "Nebraska",
    stateCode: "NE",
    medianSalary: 49800,
    population: 295222,
  },
  "bellevue": {
    name: "Bellevue",
    state: "Nebraska",
    stateCode: "NE",
    medianSalary: 48980,
    population: 120000,
  },
  "grand-island": {
    name: "Grand Island",
    state: "Nebraska",
    stateCode: "NE",
    medianSalary: 49410,
    population: 120000,
  },
  "kearney": {
    name: "Kearney",
    state: "Nebraska",
    stateCode: "NE",
    medianSalary: 48980,
    population: 120000,
  },
  "nashua": {
    name: "Nashua",
    state: "New Hampshire",
    stateCode: "NH",
    medianSalary: 56530,
    population: 91322,
  },
  "concord": {
    name: "Concord",
    state: "New Hampshire",
    stateCode: "NH",
    medianSalary: 55880,
    population: 120000,
  },
  "derry": {
    name: "Derry",
    state: "New Hampshire",
    stateCode: "NH",
    medianSalary: 55880,
    population: 34317,
  },
  "dover-nh": {
    name: "Dover",
    state: "New Hampshire",
    stateCode: "NH",
    medianSalary: 55880,
    population: 31145,
  },
  "jersey-city": {
    name: "Jersey City",
    state: "New Jersey",
    stateCode: "NJ",
    medianSalary: 61430,
    population: 292449,
  },
  "paterson": {
    name: "Paterson",
    state: "New Jersey",
    stateCode: "NJ",
    medianSalary: 58570,
    population: 120000,
  },
  "elizabeth": {
    name: "Elizabeth",
    state: "New Jersey",
    stateCode: "NJ",
    medianSalary: 58570,
    population: 120000,
  },
  "trenton": {
    name: "Trenton",
    state: "New Jersey",
    stateCode: "NJ",
    medianSalary: 63490,
    population: 120000,
  },
  "bismarck": {
    name: "Bismarck",
    state: "North Dakota",
    stateCode: "ND",
    medianSalary: 52560,
    population: 77640,
  },
  "grand-forks": {
    name: "Grand Forks",
    state: "North Dakota",
    stateCode: "ND",
    medianSalary: 49760,
    population: 120000,
  },
  "minot": {
    name: "Minot",
    state: "North Dakota",
    stateCode: "ND",
    medianSalary: 48940,
    population: 120000,
  },
  "west-fargo": {
    name: "West Fargo",
    state: "North Dakota",
    stateCode: "ND",
    medianSalary: 51050,
    population: 120000,
  },
  "cranston": {
    name: "Cranston",
    state: "Rhode Island",
    stateCode: "RI",
    medianSalary: 56780,
    population: 120000,
  },
  "warwick": {
    name: "Warwick",
    state: "Rhode Island",
    stateCode: "RI",
    medianSalary: 53680,
    population: 120000,
  },
  "pawtucket": {
    name: "Pawtucket",
    state: "Rhode Island",
    stateCode: "RI",
    medianSalary: 56780,
    population: 120000,
  },
  "east-providence": {
    name: "East Providence",
    state: "Rhode Island",
    stateCode: "RI",
    medianSalary: 53680,
    population: 120000,
  },
  "charleston": {
    name: "Charleston",
    state: "South Carolina",
    stateCode: "SC",
    medianSalary: 49150,
    population: 120000,
  },
  "north-charleston": {
    name: "North Charleston",
    state: "South Carolina",
    stateCode: "SC",
    medianSalary: 49150,
    population: 114852,
  },
  "greenville-sc": {
    name: "Greenville",
    state: "South Carolina",
    stateCode: "SC",
    medianSalary: 46580,
    population: 72085,
  },
  "spartanburg": {
    name: "Spartanburg",
    state: "South Carolina",
    stateCode: "SC",
    medianSalary: 47650,
    population: 120000,
  },
  "rapid-city": {
    name: "Rapid City",
    state: "South Dakota",
    stateCode: "SD",
    medianSalary: 46270,
    population: 77956,
  },
  "aberdeen-sd": {
    name: "Aberdeen",
    state: "South Dakota",
    stateCode: "SD",
    medianSalary: 47080,
    population: 120000,
  },
  "brookings": {
    name: "Brookings",
    state: "South Dakota",
    stateCode: "SD",
    medianSalary: 47080,
    population: 120000,
  },
  "watertown-sd": {
    name: "Watertown",
    state: "South Dakota",
    stateCode: "SD",
    medianSalary: 47080,
    population: 120000,
  },
  "south-burlington": {
    name: "South Burlington",
    state: "Vermont",
    stateCode: "VT",
    medianSalary: 60020,
    population: 20292,
  },
  "rutland": {
    name: "Rutland",
    state: "Vermont",
    stateCode: "VT",
    medianSalary: 56390,
    population: 15310,
  },
  "barre": {
    name: "Barre",
    state: "Vermont",
    stateCode: "VT",
    medianSalary: 56390,
    population: 8552,
  },
  "montpelier": {
    name: "Montpelier",
    state: "Vermont",
    stateCode: "VT",
    medianSalary: 56390,
    population: 7855,
  },
  "huntington-wv": {
    name: "Huntington",
    state: "West Virginia",
    stateCode: "WV",
    medianSalary: 44600,
    population: 120000,
  },
  "parkersburg": {
    name: "Parkersburg",
    state: "West Virginia",
    stateCode: "WV",
    medianSalary: 42000,
    population: 120000,
  },
  "morgantown": {
    name: "Morgantown",
    state: "West Virginia",
    stateCode: "WV",
    medianSalary: 47350,
    population: 120000,
  },
  "wheeling": {
    name: "Wheeling",
    state: "West Virginia",
    stateCode: "WV",
    medianSalary: 44250,
    population: 120000,
  },
  "casper": {
    name: "Casper",
    state: "Wyoming",
    stateCode: "WY",
    medianSalary: 48880,
    population: 57461,
  },
  "laramie": {
    name: "Laramie",
    state: "Wyoming",
    stateCode: "WY",
    medianSalary: 50270,
    population: 32158,
  },
  "gillette": {
    name: "Gillette",
    state: "Wyoming",
    stateCode: "WY",
    medianSalary: 50270,
    population: 32857,
  },
  "rock-springs": {
    name: "Rock Springs",
    state: "Wyoming",
    stateCode: "WY",
    medianSalary: 50270,
    population: 23640,
  },
  "aurora": {
    name: "Aurora",
    state: "Colorado",
    stateCode: "CO",
    medianSalary: 62320,
    population: 366623,
  },
  "fort-collins": {
    name: "Fort Collins",
    state: "Colorado",
    stateCode: "CO",
    medianSalary: 55310,
    population: 164245,
  },
  "aurora-il": {
    name: "Aurora",
    state: "Illinois",
    stateCode: "IL",
    medianSalary: 51960,
    population: 120000,
  },
  "naperville": {
    name: "Naperville",
    state: "Illinois",
    stateCode: "IL",
    medianSalary: 54720,
    population: 120000,
  },
  "rockford": {
    name: "Rockford",
    state: "Illinois",
    stateCode: "IL",
    medianSalary: 47120,
    population: 120000,
  },
  "st-louis": {
    name: "St. Louis",
    state: "Missouri",
    stateCode: "MO",
    medianSalary: 49990,
    population: 293310,
  },
  "springfield-mo": {
    name: "Springfield",
    state: "Missouri",
    stateCode: "MO",
    medianSalary: 45780,
    population: 169176,
  },
  "columbia-mo": {
    name: "Columbia",
    state: "Missouri",
    stateCode: "MO",
    medianSalary: 47260,
    population: 126254,
  },
  "henderson": {
    name: "Henderson",
    state: "Nevada",
    stateCode: "NV",
    medianSalary: 46670,
    population: 317610,
  },
  "reno": {
    name: "Reno",
    state: "Nevada",
    stateCode: "NV",
    medianSalary: 49660,
    population: 264165,
  },
  "north-las-vegas": {
    name: "North Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    medianSalary: 46670,
    population: 261874,
  },
  "buffalo": {
    name: "Buffalo",
    state: "New York",
    stateCode: "NY",
    medianSalary: 50790,
    population: 276807,
  },
  "rochester": {
    name: "Rochester",
    state: "New York",
    stateCode: "NY",
    medianSalary: 51210,
    population: 206284,
  },
  "yonkers": {
    name: "Yonkers",
    state: "New York",
    stateCode: "NY",
    medianSalary: 59670,
    population: 120000,
  },
  "cincinnati": {
    name: "Cincinnati",
    state: "Ohio",
    stateCode: "OH",
    medianSalary: 50170,
    population: 309317,
  },
  "cleveland": {
    name: "Cleveland",
    state: "Ohio",
    stateCode: "OH",
    medianSalary: 50140,
    population: 372624,
  },
  "dayton-oh": {
    name: "Dayton",
    state: "Ohio",
    stateCode: "OH",
    medianSalary: 49980,
    population: 120000,
  },
  "pittsburgh": {
    name: "Pittsburgh",
    state: "Pennsylvania",
    stateCode: "PA",
    medianSalary: 49650,
    population: 302971,
  },
  "allentown": {
    name: "Allentown",
    state: "Pennsylvania",
    stateCode: "PA",
    medianSalary: 48990,
    population: 120000,
  },
  "erie": {
    name: "Erie",
    state: "Pennsylvania",
    stateCode: "PA",
    medianSalary: 44460,
    population: 120000,
  },
  "knoxville": {
    name: "Knoxville",
    state: "Tennessee",
    stateCode: "TN",
    medianSalary: 47080,
    population: 190740,
  },
  "chattanooga": {
    name: "Chattanooga",
    state: "Tennessee",
    stateCode: "TN",
    medianSalary: 46700,
    population: 181099,
  },
  "provo": {
    name: "Provo",
    state: "Utah",
    stateCode: "UT",
    medianSalary: 48010,
    population: 115162,
  },
  "west-valley-city": {
    name: "West Valley City",
    state: "Utah",
    stateCode: "UT",
    medianSalary: 50110,
    population: 140230,
  },
  "west-jordan": {
    name: "West Jordan",
    state: "Utah",
    stateCode: "UT",
    medianSalary: 50110,
    population: 116961,
  },
  "virginia-beach": {
    name: "Virginia Beach",
    state: "Virginia",
    stateCode: "VA",
    medianSalary: 49430,
    population: 459470,
  },
  "norfolk": {
    name: "Norfolk",
    state: "Virginia",
    stateCode: "VA",
    medianSalary: 49430,
    population: 238005,
  },
  "chesapeake": {
    name: "Chesapeake",
    state: "Virginia",
    stateCode: "VA",
    medianSalary: 49430,
    population: 247697,
  },
  "spokane": {
    name: "Spokane",
    state: "Washington",
    stateCode: "WA",
    medianSalary: 54660,
    population: 228989,
  },
  "tacoma": {
    name: "Tacoma",
    state: "Washington",
    stateCode: "WA",
    medianSalary: 72610,
    population: 219346,
  },
  "bellevue-wa": {
    name: "Bellevue",
    state: "Washington",
    stateCode: "WA",
    medianSalary: 72610,
    population: 120000,
  },
  "madison": {
    name: "Madison",
    state: "Wisconsin",
    stateCode: "WI",
    medianSalary: 58080,
    population: 269840,
  },
  "green-bay": {
    name: "Green Bay",
    state: "Wisconsin",
    stateCode: "WI",
    medianSalary: 49940,
    population: 107395,
  },
  "kenosha": {
    name: "Kenosha",
    state: "Wisconsin",
    stateCode: "WI",
    medianSalary: 48310,
    population: 100150,
  },
  "san-jose": {
    name: "San Jose",
    state: "California",
    stateCode: "CA",
    medianSalary: 84050,
    population: 1013240,
  },
  "fresno": {
    name: "Fresno",
    state: "California",
    stateCode: "CA",
    medianSalary: 46910,
    population: 542107,
  },
  "long-beach": {
    name: "Long Beach",
    state: "California",
    stateCode: "CA",
    medianSalary: 55850,
    population: 466742,
  },
  "mesa": {
    name: "Mesa",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 51380,
    population: 120000,
  },
  "chandler": {
    name: "Chandler",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 51380,
    population: 270750,
  },
  "scottsdale": {
    name: "Scottsdale",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 50060,
    population: 258069,
  },
  "savannah": {
    name: "Savannah",
    state: "Georgia",
    stateCode: "GA",
    medianSalary: 47240,
    population: 120000,
  },
  "columbus-ga": {
    name: "Columbus",
    state: "Georgia",
    stateCode: "GA",
    medianSalary: 43540,
    population: 196671,
  },
  "augusta": {
    name: "Augusta",
    state: "Georgia",
    stateCode: "GA",
    medianSalary: 45990,
    population: 120000,
  },
  "fort-lauderdale": {
    name: "Fort Lauderdale",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 48640,
    population: 185494,
  },
  "st-petersburg": {
    name: "St. Petersburg",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 48940,
    population: 265351,
  },
  "hialeah": {
    name: "Hialeah",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 47880,
    population: 236387,
  },
  "greensboro": {
    name: "Greensboro",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 46570,
    population: 296710,
  },
  "durham-nc": {
    name: "Durham",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 60720,
    population: 278993,
  },
  "winston-salem": {
    name: "Winston-Salem",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 46380,
    population: 247945,
  },
};

export const CITY_SLUGS = Object.keys(CITY_DATA);
