// ============================================================
// CITY SALARY DATA — BLS 2024 Metro Area Medians
// salaryfact.com
// 181 US metros
// ============================================================

export interface CityData {
  name: string;
  state: string;
  stateCode: string;
  medianSalary: number;
  population: number;
}

export const CITY_DATA: Record<string, CityData> = {
  "houston": {
    name: "Houston",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 45000,
    population: 2304580,
  },
  "san-antonio": {
    name: "San Antonio",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 42000,
    population: 1434625,
  },
  "dallas": {
    name: "Dallas",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 49000,
    population: 1304379,
  },
  "austin": {
    name: "Austin",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 59000,
    population: 961855,
  },
  "fort-worth": {
    name: "Fort Worth",
    state: "Texas",
    stateCode: "TX",
    medianSalary: 46000,
    population: 927720,
  },
  "phoenix": {
    name: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 48000,
    population: 1608139,
  },
  "tucson": {
    name: "Tucson",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 37000,
    population: 542629,
  },
  "los-angeles": {
    name: "Los Angeles",
    state: "California",
    stateCode: "CA",
    medianSalary: 55000,
    population: 3979576,
  },
  "san-diego": {
    name: "San Diego",
    state: "California",
    stateCode: "CA",
    medianSalary: 63000,
    population: 1386932,
  },
  "san-francisco": {
    name: "San Francisco",
    state: "California",
    stateCode: "CA",
    medianSalary: 94000,
    population: 873965,
  },
  "sacramento": {
    name: "Sacramento",
    state: "California",
    stateCode: "CA",
    medianSalary: 53000,
    population: 524943,
  },
  "denver": {
    name: "Denver",
    state: "Colorado",
    stateCode: "CO",
    medianSalary: 56000,
    population: 715522,
  },
  "chicago": {
    name: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    medianSalary: 47000,
    population: 2693976,
  },
  "atlanta": {
    name: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    medianSalary: 52000,
    population: 498715,
  },
  "miami": {
    name: "Miami",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 42000,
    population: 467963,
  },
  "tampa": {
    name: "Tampa",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 45000,
    population: 399700,
  },
  "orlando": {
    name: "Orlando",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 44000,
    population: 307573,
  },
  "jacksonville": {
    name: "Jacksonville",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 43000,
    population: 949611,
  },
  "charlotte": {
    name: "Charlotte",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 52000,
    population: 874579,
  },
  "raleigh": {
    name: "Raleigh",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 56000,
    population: 467665,
  },
  "nashville": {
    name: "Nashville",
    state: "Tennessee",
    stateCode: "TN",
    medianSalary: 52000,
    population: 689447,
  },
  "memphis": {
    name: "Memphis",
    state: "Tennessee",
    stateCode: "TN",
    medianSalary: 35000,
    population: 633104,
  },
  "las-vegas": {
    name: "Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    medianSalary: 45000,
    population: 641903,
  },
  "seattle": {
    name: "Seattle",
    state: "Washington",
    stateCode: "WA",
    medianSalary: 79000,
    population: 737255,
  },
  "portland": {
    name: "Portland",
    state: "Oregon",
    stateCode: "OR",
    medianSalary: 55000,
    population: 652503,
  },
  "minneapolis": {
    name: "Minneapolis",
    state: "Minnesota",
    stateCode: "MN",
    medianSalary: 56000,
    population: 429606,
  },
  "columbus": {
    name: "Columbus",
    state: "Ohio",
    stateCode: "OH",
    medianSalary: 45000,
    population: 905748,
  },
  "indianapolis": {
    name: "Indianapolis",
    state: "Indiana",
    stateCode: "IN",
    medianSalary: 42000,
    population: 887642,
  },
  "detroit": {
    name: "Detroit",
    state: "Michigan",
    stateCode: "MI",
    medianSalary: 27000,
    population: 632464,
  },
  "philadelphia": {
    name: "Philadelphia",
    state: "Pennsylvania",
    stateCode: "PA",
    medianSalary: 40000,
    population: 1603797,
  },
  "new-york-city": {
    name: "New York City",
    state: "New York",
    stateCode: "NY",
    medianSalary: 50000,
    population: 120000,
  },
  "boston": {
    name: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    medianSalary: 71000,
    population: 675647,
  },
  "baltimore": {
    name: "Baltimore",
    state: "Maryland",
    stateCode: "MD",
    medianSalary: 42000,
    population: 585708,
  },
  "louisville": {
    name: "Louisville",
    state: "Kentucky",
    stateCode: "KY",
    medianSalary: 42000,
    population: 633045,
  },
  "kansas-city": {
    name: "Kansas City",
    state: "Missouri",
    stateCode: "MO",
    medianSalary: 45000,
    population: 508090,
  },
  "salt-lake-city": {
    name: "Salt Lake City",
    state: "Utah",
    stateCode: "UT",
    medianSalary: 58000,
    population: 213641,
  },
  "richmond": {
    name: "Richmond",
    state: "Virginia",
    stateCode: "VA",
    medianSalary: 48000,
    population: 120000,
  },
  "albuquerque": {
    name: "Albuquerque",
    state: "New Mexico",
    stateCode: "NM",
    medianSalary: 41000,
    population: 564559,
  },
  "oklahoma-city": {
    name: "Oklahoma City",
    state: "Oklahoma",
    stateCode: "OK",
    medianSalary: 42000,
    population: 681054,
  },
  "milwaukee": {
    name: "Milwaukee",
    state: "Wisconsin",
    stateCode: "WI",
    medianSalary: 37000,
    population: 577222,
  },
  "montgomery": {
    name: "Montgomery",
    state: "Alabama",
    stateCode: "AL",
    medianSalary: 35000,
    population: 199518,
  },
  "huntsville": {
    name: "Huntsville",
    state: "Alabama",
    stateCode: "AL",
    medianSalary: 49000,
    population: 120000,
  },
  "mobile": {
    name: "Mobile",
    state: "Alabama",
    stateCode: "AL",
    medianSalary: 33000,
    population: 187041,
  },
  "tuscaloosa": {
    name: "Tuscaloosa",
    state: "Alabama",
    stateCode: "AL",
    medianSalary: 36000,
    population: 120000,
  },
  "fairbanks": {
    name: "Fairbanks",
    state: "Alaska",
    stateCode: "AK",
    medianSalary: 52000,
    population: 31757,
  },
  "juneau": {
    name: "Juneau",
    state: "Alaska",
    stateCode: "AK",
    medianSalary: 62000,
    population: 32255,
  },
  "sitka": {
    name: "Sitka",
    state: "Alaska",
    stateCode: "AK",
    medianSalary: 54000,
    population: 8756,
  },
  "ketchikan": {
    name: "Ketchikan",
    state: "Alaska",
    stateCode: "AK",
    medianSalary: 50000,
    population: 8250,
  },
  "fort-smith": {
    name: "Fort Smith",
    state: "Arkansas",
    stateCode: "AR",
    medianSalary: 35000,
    population: 88037,
  },
  "fayetteville": {
    name: "Fayetteville",
    state: "Arkansas",
    stateCode: "AR",
    medianSalary: 45000,
    population: 120000,
  },
  "springdale": {
    name: "Springdale",
    state: "Arkansas",
    stateCode: "AR",
    medianSalary: 42000,
    population: 87730,
  },
  "jonesboro": {
    name: "Jonesboro",
    state: "Arkansas",
    stateCode: "AR",
    medianSalary: 37000,
    population: 78576,
  },
  "new-haven": {
    name: "New Haven",
    state: "Connecticut",
    stateCode: "CT",
    medianSalary: 39000,
    population: 130322,
  },
  "hartford": {
    name: "Hartford",
    state: "Connecticut",
    stateCode: "CT",
    medianSalary: 35000,
    population: 121054,
  },
  "stamford": {
    name: "Stamford",
    state: "Connecticut",
    stateCode: "CT",
    medianSalary: 73000,
    population: 135470,
  },
  "waterbury": {
    name: "Waterbury",
    state: "Connecticut",
    stateCode: "CT",
    medianSalary: 36000,
    population: 120000,
  },
  "dover": {
    name: "Dover",
    state: "Delaware",
    stateCode: "DE",
    medianSalary: 42000,
    population: 120000,
  },
  "newark-de": {
    name: "Newark",
    state: "Delaware",
    stateCode: "DE",
    medianSalary: 46000,
    population: 33398,
  },
  "middletown": {
    name: "Middletown",
    state: "Delaware",
    stateCode: "DE",
    medianSalary: 59000,
    population: 120000,
  },
  "smyrna": {
    name: "Smyrna",
    state: "Delaware",
    stateCode: "DE",
    medianSalary: 47000,
    population: 120000,
  },
  "hilo": {
    name: "Hilo",
    state: "Hawaii",
    stateCode: "HI",
    medianSalary: 45000,
    population: 44060,
  },
  "kailua": {
    name: "Kailua",
    state: "Hawaii",
    stateCode: "HI",
    medianSalary: 83000,
    population: 38635,
  },
  "pearl-city": {
    name: "Pearl City",
    state: "Hawaii",
    stateCode: "HI",
    medianSalary: 66000,
    population: 47698,
  },
  "waipahu": {
    name: "Waipahu",
    state: "Hawaii",
    stateCode: "HI",
    medianSalary: 61000,
    population: 120000,
  },
  "meridian": {
    name: "Meridian",
    state: "Idaho",
    stateCode: "ID",
    medianSalary: 59000,
    population: 117635,
  },
  "nampa": {
    name: "Nampa",
    state: "Idaho",
    stateCode: "ID",
    medianSalary: 45000,
    population: 112300,
  },
  "idaho-falls": {
    name: "Idaho Falls",
    state: "Idaho",
    stateCode: "ID",
    medianSalary: 43000,
    population: 65274,
  },
  "pocatello": {
    name: "Pocatello",
    state: "Idaho",
    stateCode: "ID",
    medianSalary: 37000,
    population: 57776,
  },
  "cedar-rapids": {
    name: "Cedar Rapids",
    state: "Iowa",
    stateCode: "IA",
    medianSalary: 43000,
    population: 137710,
  },
  "davenport": {
    name: "Davenport",
    state: "Iowa",
    stateCode: "IA",
    medianSalary: 40000,
    population: 99685,
  },
  "sioux-city": {
    name: "Sioux City",
    state: "Iowa",
    stateCode: "IA",
    medianSalary: 40000,
    population: 82684,
  },
  "iowa-city": {
    name: "Iowa City",
    state: "Iowa",
    stateCode: "IA",
    medianSalary: 49000,
    population: 74398,
  },
  "overland-park": {
    name: "Overland Park",
    state: "Kansas",
    stateCode: "KS",
    medianSalary: 65000,
    population: 197238,
  },
  "topeka": {
    name: "Topeka",
    state: "Kansas",
    stateCode: "KS",
    medianSalary: 37000,
    population: 126587,
  },
  "olathe": {
    name: "Olathe",
    state: "Kansas",
    stateCode: "KS",
    medianSalary: 63000,
    population: 141290,
  },
  "lawrence": {
    name: "Lawrence",
    state: "Kansas",
    stateCode: "KS",
    medianSalary: 42000,
    population: 120000,
  },
  "baton-rouge": {
    name: "Baton Rouge",
    state: "Louisiana",
    stateCode: "LA",
    medianSalary: 40000,
    population: 227470,
  },
  "shreveport": {
    name: "Shreveport",
    state: "Louisiana",
    stateCode: "LA",
    medianSalary: 35000,
    population: 178097,
  },
  "lafayette": {
    name: "Lafayette",
    state: "Louisiana",
    stateCode: "LA",
    medianSalary: 40000,
    population: 120000,
  },
  "lake-charles": {
    name: "Lake Charles",
    state: "Louisiana",
    stateCode: "LA",
    medianSalary: 37000,
    population: 120000,
  },
  "lewiston": {
    name: "Lewiston",
    state: "Maine",
    stateCode: "ME",
    medianSalary: 35000,
    population: 120000,
  },
  "bangor": {
    name: "Bangor",
    state: "Maine",
    stateCode: "ME",
    medianSalary: 37000,
    population: 31753,
  },
  "south-portland": {
    name: "South Portland",
    state: "Maine",
    stateCode: "ME",
    medianSalary: 50000,
    population: 120000,
  },
  "auburn-me": {
    name: "Auburn",
    state: "Maine",
    stateCode: "ME",
    medianSalary: 36000,
    population: 24636,
  },
  "gulfport": {
    name: "Gulfport",
    state: "Mississippi",
    stateCode: "MS",
    medianSalary: 36000,
    population: 120000,
  },
  "southaven": {
    name: "Southaven",
    state: "Mississippi",
    stateCode: "MS",
    medianSalary: 49000,
    population: 120000,
  },
  "hattiesburg": {
    name: "Hattiesburg",
    state: "Mississippi",
    stateCode: "MS",
    medianSalary: 33000,
    population: 120000,
  },
  "biloxi": {
    name: "Biloxi",
    state: "Mississippi",
    stateCode: "MS",
    medianSalary: 37000,
    population: 120000,
  },
  "missoula": {
    name: "Missoula",
    state: "Montana",
    stateCode: "MT",
    medianSalary: 45000,
    population: 79966,
  },
  "great-falls": {
    name: "Great Falls",
    state: "Montana",
    stateCode: "MT",
    medianSalary: 40000,
    population: 59434,
  },
  "bozeman": {
    name: "Bozeman",
    state: "Montana",
    stateCode: "MT",
    medianSalary: 52000,
    population: 53293,
  },
  "butte": {
    name: "Butte",
    state: "Montana",
    stateCode: "MT",
    medianSalary: 37000,
    population: 35256,
  },
  "lincoln": {
    name: "Lincoln",
    state: "Nebraska",
    stateCode: "NE",
    medianSalary: 47000,
    population: 295222,
  },
  "bellevue": {
    name: "Bellevue",
    state: "Nebraska",
    stateCode: "NE",
    medianSalary: 52000,
    population: 120000,
  },
  "grand-island": {
    name: "Grand Island",
    state: "Nebraska",
    stateCode: "NE",
    medianSalary: 42000,
    population: 120000,
  },
  "kearney": {
    name: "Kearney",
    state: "Nebraska",
    stateCode: "NE",
    medianSalary: 43000,
    population: 120000,
  },
  "nashua": {
    name: "Nashua",
    state: "New Hampshire",
    stateCode: "NH",
    medianSalary: 58000,
    population: 91322,
  },
  "concord": {
    name: "Concord",
    state: "New Hampshire",
    stateCode: "NH",
    medianSalary: 49000,
    population: 120000,
  },
  "derry": {
    name: "Derry",
    state: "New Hampshire",
    stateCode: "NH",
    medianSalary: 56000,
    population: 34317,
  },
  "dover-nh": {
    name: "Dover",
    state: "New Hampshire",
    stateCode: "NH",
    medianSalary: 50000,
    population: 31145,
  },
  "jersey-city": {
    name: "Jersey City",
    state: "New Jersey",
    stateCode: "NJ",
    medianSalary: 59000,
    population: 292449,
  },
  "paterson": {
    name: "Paterson",
    state: "New Jersey",
    stateCode: "NJ",
    medianSalary: 37000,
    population: 120000,
  },
  "elizabeth": {
    name: "Elizabeth",
    state: "New Jersey",
    stateCode: "NJ",
    medianSalary: 42000,
    population: 120000,
  },
  "trenton": {
    name: "Trenton",
    state: "New Jersey",
    stateCode: "NJ",
    medianSalary: 33000,
    population: 120000,
  },
  "bismarck": {
    name: "Bismarck",
    state: "North Dakota",
    stateCode: "ND",
    medianSalary: 49000,
    population: 77640,
  },
  "grand-forks": {
    name: "Grand Forks",
    state: "North Dakota",
    stateCode: "ND",
    medianSalary: 43000,
    population: 120000,
  },
  "minot": {
    name: "Minot",
    state: "North Dakota",
    stateCode: "ND",
    medianSalary: 45000,
    population: 120000,
  },
  "west-fargo": {
    name: "West Fargo",
    state: "North Dakota",
    stateCode: "ND",
    medianSalary: 55000,
    population: 120000,
  },
  "cranston": {
    name: "Cranston",
    state: "Rhode Island",
    stateCode: "RI",
    medianSalary: 49000,
    population: 120000,
  },
  "warwick": {
    name: "Warwick",
    state: "Rhode Island",
    stateCode: "RI",
    medianSalary: 52000,
    population: 120000,
  },
  "pawtucket": {
    name: "Pawtucket",
    state: "Rhode Island",
    stateCode: "RI",
    medianSalary: 37000,
    population: 120000,
  },
  "east-providence": {
    name: "East Providence",
    state: "Rhode Island",
    stateCode: "RI",
    medianSalary: 43000,
    population: 120000,
  },
  "charleston": {
    name: "Charleston",
    state: "South Carolina",
    stateCode: "SC",
    medianSalary: 56000,
    population: 120000,
  },
  "north-charleston": {
    name: "North Charleston",
    state: "South Carolina",
    stateCode: "SC",
    medianSalary: 42000,
    population: 114852,
  },
  "greenville-sc": {
    name: "Greenville",
    state: "South Carolina",
    stateCode: "SC",
    medianSalary: 52000,
    population: 72085,
  },
  "spartanburg": {
    name: "Spartanburg",
    state: "South Carolina",
    stateCode: "SC",
    medianSalary: 42000,
    population: 120000,
  },
  "rapid-city": {
    name: "Rapid City",
    state: "South Dakota",
    stateCode: "SD",
    medianSalary: 46000,
    population: 77956,
  },
  "aberdeen-sd": {
    name: "Aberdeen",
    state: "South Dakota",
    stateCode: "SD",
    medianSalary: 42000,
    population: 120000,
  },
  "brookings": {
    name: "Brookings",
    state: "South Dakota",
    stateCode: "SD",
    medianSalary: 42000,
    population: 120000,
  },
  "watertown-sd": {
    name: "Watertown",
    state: "South Dakota",
    stateCode: "SD",
    medianSalary: 42000,
    population: 120000,
  },
  "south-burlington": {
    name: "South Burlington",
    state: "Vermont",
    stateCode: "VT",
    medianSalary: 59000,
    population: 20292,
  },
  "rutland": {
    name: "Rutland",
    state: "Vermont",
    stateCode: "VT",
    medianSalary: 37000,
    population: 15310,
  },
  "barre": {
    name: "Barre",
    state: "Vermont",
    stateCode: "VT",
    medianSalary: 36000,
    population: 8552,
  },
  "montpelier": {
    name: "Montpelier",
    state: "Vermont",
    stateCode: "VT",
    medianSalary: 45000,
    population: 7855,
  },
  "huntington-wv": {
    name: "Huntington",
    state: "West Virginia",
    stateCode: "WV",
    medianSalary: 33000,
    population: 120000,
  },
  "parkersburg": {
    name: "Parkersburg",
    state: "West Virginia",
    stateCode: "WV",
    medianSalary: 35000,
    population: 120000,
  },
  "morgantown": {
    name: "Morgantown",
    state: "West Virginia",
    stateCode: "WV",
    medianSalary: 42000,
    population: 120000,
  },
  "wheeling": {
    name: "Wheeling",
    state: "West Virginia",
    stateCode: "WV",
    medianSalary: 32000,
    population: 120000,
  },
  "casper": {
    name: "Casper",
    state: "Wyoming",
    stateCode: "WY",
    medianSalary: 47000,
    population: 57461,
  },
  "laramie": {
    name: "Laramie",
    state: "Wyoming",
    stateCode: "WY",
    medianSalary: 42000,
    population: 32158,
  },
  "gillette": {
    name: "Gillette",
    state: "Wyoming",
    stateCode: "WY",
    medianSalary: 52000,
    population: 32857,
  },
  "rock-springs": {
    name: "Rock Springs",
    state: "Wyoming",
    stateCode: "WY",
    medianSalary: 49000,
    population: 23640,
  },
  "aurora": {
    name: "Aurora",
    state: "Colorado",
    stateCode: "CO",
    medianSalary: 50000,
    population: 366623,
  },
  "fort-collins": {
    name: "Fort Collins",
    state: "Colorado",
    stateCode: "CO",
    medianSalary: 56000,
    population: 164245,
  },
  "aurora-il": {
    name: "Aurora",
    state: "Illinois",
    stateCode: "IL",
    medianSalary: 49000,
    population: 120000,
  },
  "naperville": {
    name: "Naperville",
    state: "Illinois",
    stateCode: "IL",
    medianSalary: 76000,
    population: 120000,
  },
  "rockford": {
    name: "Rockford",
    state: "Illinois",
    stateCode: "IL",
    medianSalary: 35000,
    population: 120000,
  },
  "st-louis": {
    name: "St. Louis",
    state: "Missouri",
    stateCode: "MO",
    medianSalary: 37000,
    population: 293310,
  },
  "springfield-mo": {
    name: "Springfield",
    state: "Missouri",
    stateCode: "MO",
    medianSalary: 36000,
    population: 169176,
  },
  "columbia-mo": {
    name: "Columbia",
    state: "Missouri",
    stateCode: "MO",
    medianSalary: 42000,
    population: 126254,
  },
  "henderson": {
    name: "Henderson",
    state: "Nevada",
    stateCode: "NV",
    medianSalary: 52000,
    population: 317610,
  },
  "reno": {
    name: "Reno",
    state: "Nevada",
    stateCode: "NV",
    medianSalary: 49000,
    population: 264165,
  },
  "north-las-vegas": {
    name: "North Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    medianSalary: 43000,
    population: 261874,
  },
  "buffalo": {
    name: "Buffalo",
    state: "New York",
    stateCode: "NY",
    medianSalary: 35000,
    population: 276807,
  },
  "rochester": {
    name: "Rochester",
    state: "New York",
    stateCode: "NY",
    medianSalary: 33000,
    population: 206284,
  },
  "yonkers": {
    name: "Yonkers",
    state: "New York",
    stateCode: "NY",
    medianSalary: 45000,
    population: 120000,
  },
  "cincinnati": {
    name: "Cincinnati",
    state: "Ohio",
    stateCode: "OH",
    medianSalary: 42000,
    population: 309317,
  },
  "cleveland": {
    name: "Cleveland",
    state: "Ohio",
    stateCode: "OH",
    medianSalary: 27000,
    population: 372624,
  },
  "dayton-oh": {
    name: "Dayton",
    state: "Ohio",
    stateCode: "OH",
    medianSalary: 32000,
    population: 120000,
  },
  "pittsburgh": {
    name: "Pittsburgh",
    state: "Pennsylvania",
    stateCode: "PA",
    medianSalary: 37000,
    population: 302971,
  },
  "allentown": {
    name: "Allentown",
    state: "Pennsylvania",
    stateCode: "PA",
    medianSalary: 35000,
    population: 120000,
  },
  "erie": {
    name: "Erie",
    state: "Pennsylvania",
    stateCode: "PA",
    medianSalary: 32000,
    population: 120000,
  },
  "knoxville": {
    name: "Knoxville",
    state: "Tennessee",
    stateCode: "TN",
    medianSalary: 42000,
    population: 190740,
  },
  "chattanooga": {
    name: "Chattanooga",
    state: "Tennessee",
    stateCode: "TN",
    medianSalary: 43000,
    population: 181099,
  },
  "provo": {
    name: "Provo",
    state: "Utah",
    stateCode: "UT",
    medianSalary: 52000,
    population: 115162,
  },
  "west-valley-city": {
    name: "West Valley City",
    state: "Utah",
    stateCode: "UT",
    medianSalary: 47000,
    population: 140230,
  },
  "west-jordan": {
    name: "West Jordan",
    state: "Utah",
    stateCode: "UT",
    medianSalary: 52000,
    population: 116961,
  },
  "virginia-beach": {
    name: "Virginia Beach",
    state: "Virginia",
    stateCode: "VA",
    medianSalary: 56000,
    population: 459470,
  },
  "norfolk": {
    name: "Norfolk",
    state: "Virginia",
    stateCode: "VA",
    medianSalary: 42000,
    population: 238005,
  },
  "chesapeake": {
    name: "Chesapeake",
    state: "Virginia",
    stateCode: "VA",
    medianSalary: 58000,
    population: 247697,
  },
  "spokane": {
    name: "Spokane",
    state: "Washington",
    stateCode: "WA",
    medianSalary: 40000,
    population: 228989,
  },
  "tacoma": {
    name: "Tacoma",
    state: "Washington",
    stateCode: "WA",
    medianSalary: 49000,
    population: 219346,
  },
  "bellevue-wa": {
    name: "Bellevue",
    state: "Washington",
    stateCode: "WA",
    medianSalary: 101000,
    population: 120000,
  },
  "madison": {
    name: "Madison",
    state: "Wisconsin",
    stateCode: "WI",
    medianSalary: 52000,
    population: 269840,
  },
  "green-bay": {
    name: "Green Bay",
    state: "Wisconsin",
    stateCode: "WI",
    medianSalary: 42000,
    population: 107395,
  },
  "kenosha": {
    name: "Kenosha",
    state: "Wisconsin",
    stateCode: "WI",
    medianSalary: 43000,
    population: 100150,
  },
  "san-jose": {
    name: "San Jose",
    state: "California",
    stateCode: "CA",
    medianSalary: 97000,
    population: 1013240,
  },
  "fresno": {
    name: "Fresno",
    state: "California",
    stateCode: "CA",
    medianSalary: 40000,
    population: 542107,
  },
  "long-beach": {
    name: "Long Beach",
    state: "California",
    stateCode: "CA",
    medianSalary: 52000,
    population: 466742,
  },
  "tucson-extra": {
    name: "Mesa",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 47000,
    population: 120000,
  },
  "chandler": {
    name: "Chandler",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 59000,
    population: 270750,
  },
  "scottsdale": {
    name: "Scottsdale",
    state: "Arizona",
    stateCode: "AZ",
    medianSalary: 73000,
    population: 258069,
  },
  "savannah": {
    name: "Savannah",
    state: "Georgia",
    stateCode: "GA",
    medianSalary: 42000,
    population: 120000,
  },
  "columbus-ga": {
    name: "Columbus",
    state: "Georgia",
    stateCode: "GA",
    medianSalary: 37000,
    population: 196671,
  },
  "augusta": {
    name: "Augusta",
    state: "Georgia",
    stateCode: "GA",
    medianSalary: 36000,
    population: 120000,
  },
  "fort-lauderdale": {
    name: "Fort Lauderdale",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 49000,
    population: 185494,
  },
  "st-petersburg": {
    name: "St. Petersburg",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 45000,
    population: 265351,
  },
  "hialeah": {
    name: "Hialeah",
    state: "Florida",
    stateCode: "FL",
    medianSalary: 37000,
    population: 236387,
  },
  "greensboro": {
    name: "Greensboro",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 40000,
    population: 296710,
  },
  "durham-nc": {
    name: "Durham",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 49000,
    population: 278993,
  },
  "winston-salem": {
    name: "Winston-Salem",
    state: "North Carolina",
    stateCode: "NC",
    medianSalary: 39000,
    population: 247945,
  },
};

export const CITY_SLUGS = Object.keys(CITY_DATA);
